### ISSUE TITLE
Opening files using JetBrains built-in web server doesn't work on Firefox

### ISSUE THREAD

**Issue by lmichelin** [lmichelin/open-github-links-in-ide#21]
Currently, opening files using JetBrains built-in web server does not work on Firefox.

As suggested in #20, I tried to add a permission for `*://localhost/*` in manifest.json, but although the request is sent to the editor, it's still not working.

JetBrains shows this warning message and nothing happens after clicking on 'Yes':
![image](https://user-images.githubusercontent.com/33673240/114470228-d69bf980-9bee-11eb-87de-ed01d38f54cc.png)

With Chrome, the message is slightly different (host is recognized as github.com) and it works after clicking on 'Yes':
![image](https://user-images.githubusercontent.com/33673240/114470360-0ba84c00-9bef-11eb-81c6-d68d6f9daac0.png)

**Comment by ekatz-quotient** [comment]
Do you get this message when the `*://localhost/*` permission is absent?
I didn't try to run it yet, but when I just enter the link from the address bar it works and the correct file opens.
Did you check "Allow unsigned requests" and "Can accept external connections" in IntelliJ's debugger settings?

**Comment by lmichelin** [comment]
No, I get this message on the IDE when the `*://localhost/*` permission is added.
When the permission is not added, the request fails (I get this alert from the browser):
![image](https://user-images.githubusercontent.com/33673240/114521818-0ffe5480-9c43-11eb-9261-cd934b3fe252.png)

With the permission added, I tried to :
- check "Allow unsigned requests" -> the message disappears but nothing happens when trying to open a file
- change the port and check "Can accept external connections" -> no impact

**Comment by ekatz-quotient** [comment]
Try changing the port back (the "Can accept external connections" becomes disabled but is still checked).
Since the permission is required anyway (otherwise the request doesn't even reach the IDE), can you please merge #20?
Thanks

**Comment by lmichelin** [comment]
Same issue if I change back the port :confused:

**Comment by lmichelin** [comment]
Actually it was an error on my side, the local repositories path was wrong in the extension settings :see_no_evil:
It's working now with the *Allow unsigned requests* option checked ;)

**Comment by lmichelin** [comment]
Fixed by #20
