### ISSUE TITLE
reload required for every github page to display Webstorm icon

### ISSUE THREAD

**Issue by charleskoehl** [lmichelin/open-github-links-in-ide#35]
To repro:
1. open a PR
2. click Review Changes button
3. mouse over any line: the [+] icon appears to add a comment, but no webstorm icon
4. reload the page
5. webstorm icons appear

Reloading is required whenever a page is navigated to that should show the icon.

I've already added a personal github token as well.

Mac OS X v 12.4
Chrome Version 103.0.5060.114 (Official Build) (x86_64)

**Comment by lmichelin** [comment]
Hello @charleskoehl, I fixed this issue in v1.2.0. Could you confirm that it's working now on your side ? Thanks 😉
