### ISSUE TITLE
Vivaldi / Chrome Path Does Not Exist 

### ISSUE THREAD

**Issue by evanricard** [lmichelin/open-github-links-in-ide#7]
Hey @lmichelin, THANK you for an addition like this because the "open" in Visual Studio button has given me issues for such a long time.

![image](https://user-images.githubusercontent.com/30779615/71313676-fe6bba80-2409-11ea-9f4c-9b0928dfe470.png)

However, with every attempt to open a file / folder in VSCode was met with the same error. As an example, I cloned, unzipped your directory, and then moved it all around including taking it to the "home" part of my C: drive - ~\users\<user> - while still trying to open it with your open-in-ide function...is there something I am missing?

Regardless, merry Christmas and thanks again!

**Comment by lmichelin** [comment]
Hello @evanricard,

If you cloned the repository into your "home" folder on Windows (`C:\Users\<user>\open-github-links-in-ide`), you need to put `C:\Users\<user>` in the local path field (accessible by clicking on the extension icon):

![image](https://user-images.githubusercontent.com/33673240/71314329-b3bc6380-2446-11ea-9278-7e9098d8cfad.png)

Feel free to ask me more details if it doesn't solve your issue :)

**Comment by evanricard** [comment]
Oh my gosh I completely missed that I went looking for options under my extensions instead of just clicking your icon @lmichelin...apparently I am doing too much computer work during the holidays - thank you!
